import SiteHeader from '../site-header';

const projects = [
  { id: 'inspectpro', type: 'Mobile engineering', status: 'Completed', title: 'InspectPro', description: 'A field app for engineers to capture work progress with images, GPS metadata, and export structured PDFs for audits. Built to handle low-network environments.', tech: ['Flutter', 'Hive', 'Cloud'], links: [['View source ↗', 'https://github.com/sridharpandiarajan/inspectpro.git']] },
  { id: 'stafia', type: 'CRM system', status: 'In progress', title: 'Stafia-CRM', description: 'A WhatsApp-first lead automation system designed to centralize inquiries and prevent lead leakage. Features include smart follow-up reminders, custom pipeline stages, activity timelines, and one-click WhatsApp workflows for non-technical business owners.', tech: ['React', 'Next.js', 'Supabase', 'WhatsApp API'], links: [['Live demo ↗', 'https://stafia.vercel.app']] },
  { id: 'docscode', type: 'Full stack system', status: 'Completed', title: 'Doc’s Code', description: 'Doctor-friendly system to manage patient records, prescriptions, and visit history. Includes role-based authentication and secure cloud backups.', tech: ['React', 'Node.js', 'MongoDB'], links: [['Live demo ↗', 'https://docscode.vercel.app'], ['View source ↗', 'https://github.com/sridharpandiarajan/DOCSCODE.git']] },
];

export default function ProjectsPage() {
  return <><SiteHeader /><main className="projects-page section-wrap"><p className="eyebrow">Portfolio / Selected work</p><h1>Projects &<br /><em>experiments.</em></h1><p className="projects-intro">A collection of products and systems built across mobile engineering, CRM, and full stack development.</p><div className="project-list">{projects.map((project, i) => <article className="project" id={project.id} key={project.id}><span className="project-index">0{i + 1}</span><div className="project-main"><div className="project-meta"><span>{project.type}</span><span className={`project-status ${project.status === 'In progress' ? 'in-progress' : ''}`}>{project.status}</span></div><h2>{project.title}</h2><p>{project.description}</p><div className="tech-list">{project.tech.map(tech => <span key={tech}>{tech}</span>)}</div></div><div className="project-links">{project.links.map(([label, href]) => <a key={href} href={href} target="_blank" rel="noreferrer">{label}</a>)}</div></article>)}</div><a className="text-link projects-back" href="/#home">← Back to home</a></main><footer className="projects-footer"><span>© {new Date().getFullYear()} Sridhar Pandiarajan</span><span>Chennai, India</span></footer></>;
}
