import SiteHeader from './site-header';

const skillGroups = [
  { category: 'Interface & mobile', skills: ['React', 'Next.js', 'Vue.js', 'Flutter', 'HTML & CSS', 'Tailwind'] },
  { category: 'Backend & platforms', skills: ['Node.js', 'Express', 'MongoDB', 'SQL', 'Firebase', 'Git'] },
  { category: 'Data & visualization', skills: ['Python', 'Pandas', 'Seaborn', 'Power BI', 'Tableau'] },
];
const projects = [
  { id: 'inspectpro', type: 'Mobile engineering', status: 'Completed', title: 'InspectPro', description: 'A field app for engineers to capture work progress with images, GPS metadata, and export structured PDFs for audits. Built to handle low-network environments.', tech: ['Flutter', 'Hive', 'Cloud'], href: 'https://github.com/sridharpandiarajan/inspectpro.git', label: 'View source ↗' },
  { id: 'stafia', type: 'CRM system', status: 'In progress', title: 'Stafia-CRM', description: 'A WhatsApp-first lead automation system designed to centralize inquiries and prevent lead leakage. Includes follow-up reminders, pipeline stages, activity timelines, and one-click WhatsApp workflows.', tech: ['React', 'Next.js', 'Supabase', 'WhatsApp API'], href: 'https://stafia.vercel.app', label: 'Live demo ↗' },
  { id: 'docscode', type: 'Full stack system', status: 'Completed', title: 'Doc’s Code', description: 'Doctor-friendly system to manage patient records, prescriptions, and visit history. Includes role-based authentication and secure cloud backups.', tech: ['React', 'Node.js', 'MongoDB'], href: 'https://docscode.vercel.app', label: 'Live demo ↗', source: 'https://github.com/sridharpandiarajan/DOCSCODE.git' },
];

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero section-wrap" id="home">
      <div className="hero-copy">
        <p className="eyebrow"><span className="status-dot" /> Product developer <span className="eyebrow-divider">/</span> Chennai, India</p>
        <h1>I make complex<br />work feel <span className="serif-italic">simple.</span></h1>
        <p className="hero-intro">I’m Sridhar, a Product Developer Intern at Intellea. I build practical digital tools across HR, payroll, learning, and attendance.</p>
        <div className="hero-actions"><a className="button button-dark" href="#projects">Explore my work <span aria-hidden="true">↘</span></a><a className="text-link" href="/assets/Sridhar_Pandiarajan_Resume.pdf" target="_blank" rel="noreferrer">View résumé <span aria-hidden="true">↗</span></a></div>
        <div className="hero-proof"><span>From idea</span><i aria-hidden="true" /><span>to a tool people can use</span></div>
      </div>
      <div className="hero-art-column">
        <div className="hero-visual" aria-label="Sridhar Pandiarajan, Product Developer">
          <div className="hero-visual-head"><span>Currently building</span><span className="hero-visual-mark">SP<span>↗</span></span></div>
          <div className="hero-disc" />
          <img className="hero-portrait" src="/assets/profile.png" alt="Portrait of Sridhar Pandiarajan" />
          <div className="hero-float-card"><span className="float-card-label">At Intellea</span><strong>Useful systems.<br />Thoughtful details.</strong><span className="float-card-arrow">↗</span></div>
        </div>
        <div className="hero-visual-foot"><span>PRODUCT · WEB · MOBILE</span><span>01 / 01</span></div>
      </div>
      <div className="hero-bottom"><span>Scroll to explore</span><span>Chennai, India&nbsp; ↘</span></div>
    </section>

    <section className="about section-wrap section-pad" id="about"><div className="section-label"><span>01 / About</span><span>Curious by nature</span></div><div className="about-grid"><h2>Building at the<br /><em>intersection</em> of<br />design & technology.</h2><div><p className="large-copy">A versatile developer specializing in cross-platform experiences. I build high-performance mobile and web applications using Flutter and modern frameworks like React, backed by robust serverless architectures like Firebase.</p><p className="body-copy">Beyond the interface, I bring strong backend logic with Python and turn complex datasets into actionable insights using Pandas. I enjoy untangling complexity, learning new tools, and shipping scalable software.</p><blockquote className="about-quote"><span aria-hidden="true">“</span><p>Like Ilaiyaraaja&#8217;s melodies or Kamal&#8217;s frames, real impact lies in refining the craft.<span className="quote-end" aria-hidden="true">“</span></p></blockquote></div></div></section>

    <section className="services section-pad"><div className="section-wrap"><div className="section-label"><span>02 / What I do</span><span>From idea to implementation</span></div><div className="service-grid">{[['01', 'Frontend & UI/UX', 'Responsive, accessible interfaces and seamless user experiences for web and mobile applications.'], ['02', 'Backend & architecture', 'Robust APIs, secure authentication, and scalable data architectures.'], ['03', 'Ideation & strategy', 'Turning complex ideas into clear plans and useful, deployable products.']].map(([n, title, copy]) => <article className="service" key={n}><span className="service-number">{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section-wrap section-pad skills" id="skills"><div className="section-label"><span>03 / Toolkit</span><span>Tools I reach for</span></div><div className="skills-layout"><h2>A practical<br /><em>toolkit.</em></h2><div className="skill-groups">{skillGroups.map(group => <article className="skill-group" key={group.category}><h3>{group.category}</h3><ul>{group.skills.map(skill => <li key={skill}>{skill}</li>)}</ul></article>)}</div></div></section>

    <section className="experience section-pad" id="experience"><div className="section-wrap"><div className="section-label"><span>04 / Background</span><span>Experience & education</span></div><div className="experience-grid"><div><h2>Experience</h2><article className="timeline-entry"><div className="entry-top"><div className="entry-title"><img className="company-logo intellea-logo" src="/logos/intellea%20i.jpg.jpeg" alt="" /><h3>Product Developer Intern</h3></div><span>2026 – Present</span></div><p className="entry-org">Intellea · Chennai</p><ul><li>Built HR and payroll features using FastAPI, PostgreSQL and Next.js.</li><li>Built a drag-and-drop timetable builder for the LMS with clash detection.</li><li>Integrated biometric attendance devices with leave tracking and payroll export.</li><li>Built tools to import LMS classes from spreadsheets and schedule sessions in bulk.</li><li>Developed a kiosk app for walk-in check-ins.</li><li>Designed the UI for the LMS student helpline and grievance system.</li><li>Built role-based dashboards and automated email notifications.</li></ul></article><article className="timeline-entry"><div className="entry-top"><div className="entry-title"><img className="company-logo codework-logo" src="/logos/codework.svg" alt="" /><h3>Software Intern</h3></div><span>2025 – Feb 2026</span></div><p className="entry-org">CodeWork.ai · Chennai</p><ul><li>Developed a mobile application using Flutter and Firebase.</li><li>Built responsive dashboards using React and Tailwind.</li><li>Worked on website development and chatbot integration.</li></ul></article><div className="education-block"><h2>Education</h2><article className="education-entry"><div className="entry-top"><h3>B.Tech, Information Technology</h3><span>2023 – 2027 · Present</span></div><p className="entry-org">KCG College of Technology</p><p className="education-result">CGPA 9</p></article><article className="education-entry"><div className="entry-top"><h3>11th – 12th</h3><span>2021 – 2023</span></div><p className="entry-org">Sri Chaitanya Techno School · Perumbakkam</p><p className="education-result">431 / 500</p></article></div></div><div><h2>Milestones</h2><article className="milestone"><span>2023–2024</span><div><h3>Hackathons</h3><p>Participated in multiple hackathons (2023–2024).</p></div></article><article className="milestone"><span>Projects</span><div><h3>Personal & academic</h3><p>Built and deployed multiple personal and academic projects.</p></div></article><article className="milestone"><span>Academics</span><div><h3>Academic performance</h3><p>Strong academic performance with consistent top CGPA.</p></div></article></div></div></div></section>

    <section className="section-wrap section-pad work" id="projects"><div className="section-label"><span>05 / Selected work</span><span>Products & experiments</span></div><div className="work-heading"><h2>Things I’ve<br /><em>put into the world.</em></h2><p>A few systems and products I’ve built while sharpening my craft.</p></div><div className="project-list">{projects.map((project, i) => <article className="project" id={project.id} key={project.id}><span className="project-index">0{i + 1}</span><div className="project-main"><div className="project-meta"><span>{project.type}</span><span className={`project-status ${project.status === 'In progress' ? 'in-progress' : ''}`}>{project.status}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="tech-list">{project.tech.map(item => <span key={item}>{item}</span>)}</div></div><div className="project-links"><a href={project.href} target="_blank" rel="noreferrer">{project.label}</a>{project.source && <a href={project.source} target="_blank" rel="noreferrer">Source ↗</a>}</div></article>)}</div><a className="all-projects" href="/projects">Browse all project details <span>↗</span></a></section>

    <section className="contact section-pad" id="contact"><div className="section-wrap"><div className="section-label"><span>06 / Say hello</span><span>Currently open to good ideas</span></div><div className="contact-row"><div><p className="eyebrow">Have a project in mind?</p><h2>Let’s make<br /><em>something useful.</em></h2></div><div className="contact-links"><a href="mailto:sridhar.pan05@gmail.com">sridhar.pan05@gmail.com <span>↗</span></a><a href="https://www.linkedin.com/in/sridharpan/" target="_blank" rel="noreferrer">LinkedIn <span>↗</span></a><a href="https://github.com/sridharpandiarajan" target="_blank" rel="noreferrer">GitHub <span>↗</span></a><a href="https://instagram.com/sridhar_pan" target="_blank" rel="noreferrer">Instagram <span>↗</span></a></div></div><footer><span>© {new Date().getFullYear()} Sridhar Pandiarajan</span><span>Made with care in Chennai</span><a href="#home">Back to top ↑</a></footer></div></section>
  </main></>;
}
